version: '3'
services:

  web:
    build: .
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://db/myapp
    depends_on:
      - db

  db:
    image: mongo
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
